### ISSUE TITLE
Do we need curriculum-template and advanced-curriculum

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/curriculum-template#11]
It seems to me that https://github.com/isaqb-org/advanced-template and curriculum-template are almost identical and I'm wondering whether we should merge them back together. We already fixed some issues in https://github.com/isaqb-org/advanced-template which are still open in this repository.

@programming-wolf @gernotstarke @p-goetz please let me know your thoughts.

**Comment by gernotstarke** [comment]
merge it back to curriculum-template, or even simpler: remove curriculum-template.

**Comment by p-goetz** [comment]
I'm with @gernotstarke. If it doesn't spark joy, merge them.

**Comment by gernotstarke** [comment]
@aheusingfeld or @programming-wolf -> could you please perform the merge-back

**Comment by aheusingfeld** [comment]
AFAIK https://github.com/isaqb-org/advanced-template was cloned from curriculum-template in the beginning and already contains all the changes. So I‘d like to archive this repo here (instead of deleting it) in order to clearly state „this is legacy and not under active development. Rather use `advanced-template` instead“.

**Comment by gernotstarke** [comment]
I don't care WHICH one we keep active, but let's use just ONE.

**Comment by programming-wolf** [comment]
Ok, please archive/remove *this* repository. Neither Alex nor I have the permission to do so. 
Advanced module has all the changes (and more), only lacks a travis config which will be created at some point.

**Comment by gernotstarke** [comment]
will do...
