### ISSUE TITLE
build automation (aka continuous delivery)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-template#3]
create a travis/circle-ci or similar build configuration to build automatically upon pushes to certain branches

**Comment by p-goetz** [comment]
Solved as a show case. A build with travis (`.travis.yml`) generates a German and English PDF without remarks using Docker. This is then deployed as GitHub release (draft). 
Might be unnecessary since our netlify build is able to produce and publish the same content.
