### ISSUE TITLE
update build to always build every language with AND without comments

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-template#4]
build various combinations (with different output filenames):

1. EN without comments
2. EN with comments
3. DE without comments
4. DE with comments
5. DE+EN with comments

Supposedly this can work with gradle-tasks of type asciidoctor... but needs some serious gradle build expertise...

Some other projects have tried multi-project builds with asciidoctor, e.g.:

https://github.com/hibernate/hibernate-orm/blob/master/documentation/documentation.gradle#L31

https://discuss.gradle.org/t/gradle-file-structure-when-generating-multiple-output-files/6870/5

**Comment by gernotstarke** [comment]
it seems to be a real issue to rename the generated output files ...

**Comment by p-goetz** [comment]
I have solved this for this template curriculum with asciidoctor gradle post-processing. I don't like the duplication of the different tasks but couldn't find a way to extend the Asciidoctor task in a way that allows me to just configure those attributes that need to change from output to output (`language` and `withRemarks`). 
I would love for someone with more Gradle know-how to check this solution and see if there is a way to make the `build.gradle` more elegant.

**Comment by p-goetz** [comment]
Fixed by #7
